### ISSUE TITLE
New gxapi constants doc feedback

### ISSUE THREAD

**Issue by ianneilmacleod** [GeosoftInc/gxapi#1]
@jbgeosoft compare, for example:
https://geosoftinc.github.io/gxpy/9.3/python/GXAGG.html#agg-render-constants
https://geosoftinc.github.io/gxpy/9.2/python/GXAGG.html#agg-render-constants

gxapi.AGG_RENDER_ADD = 0

In 9.2 I liked the reminder that the constant is _gxapi.AGG_RENDER_ADD_, including the _gxapi_. This makes it clear that it is not the constant alone, or _gxapi.GXAGG.AGG_RENDER_ADD_, which to a Python developer would seem more logical. So the transparency of use is useful.

In 9.2 it was very useful that the value was exposed as a python developer experimenting (which is an important aspect of Python) simply enters the value, in this case 0.  I often just open a Python or iPython console and poke at a gxapi function to see how it behaves, and without auto-complete (or the habits of using it), it is fastest to just enter 0.

Worth a discussion?

**Comment by jbgeosoft** [comment]
Hi Ian, 

I can see the argument for keeping the namespace in the docs but I do not agree with your point on using values instead in code. It is a bad programming practice to use a magic value in code instead of the more descriptive constant name if available. When I read a line with the value 0 or 1 or -1 passed to a function I have to consult the docs to figure out what that means. Normally the named module attribute constant is descriptive enough to make that clear.

I also thought of putting the constants within their respective GX classes as attributes at some point but that would lead to either duplication or break backward compatibility if we remove them from the main gxapi module namespace.

I will look at the options of restoring the namespace and values (in the interest of transparency) in the docs.

Cheers,
Jacques

**Comment by ianneilmacleod** [comment]
Yes, I completely agree on your "bad practice", and in delivered modules this is important.  But when one is simply experimenting with the Python interpreter, or iPython, we are after speed of experimentation and anything that slows experimentation reduces the efficiency of experimentation. Further, these environments do not have auto-complete, so spelling mistakes further reduce speed and increase frustration for the experimenter.

**Comment by jbgeosoft** [comment]
Ah okay. Note however that iPython has auto complete (hit tab while typing). And it should actually function better than before now that the wrappers are encapsulated with Python code including the docstrings. I think with everything inside a binary module there were some issues with this in the past.

**Comment by ianneilmacleod** [comment]
I'll switch to using iPython as my primary experimentation tool.
